### PR TITLE
feat: added toast component

### PR DESCRIPTION
**Pull request by therajatg**
please review

### CODE REVIEW

**Review by iamsaurav28 — APPROVED** [review]
looks good to merge

**Review by shubhamkumar648 — COMMENTED** [review]
you can use target= _blank  inside  anchor tag so that it open in new tab

**Comment by therajatg** [comment]
Actually then I have to use target= _blank in the whole component library. Hence, I'll do it later if required.

**Review by shubhamkumar648 — APPROVED** [review]
you can merge

**Comment by shubhamkumar648** [comment]
> you can use target= _blank inside anchor tag so that it open in new tab

ok fine

**Pull request merged**
